// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxnnrxzwnhglguqohpyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bm5yeHp3bmhnbGd1cW9ocHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODMzNjcsImV4cCI6MjA4NDc1OTM2N30.U-5HznaCW4egvP4cYR6xxm3v7c8tL-3O58ugFM5KiuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});